config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: {sign_in: :login, sign_out: :logout},
              controllers: { registrations: 'users/registrations' }

  # resources :feedbacks, only: %i[index create]
  get "feedbacks" => "feedbacks#show"
  post "feedbacks" => "feedbacks#create"

  resources :tests, only: :index do
    resources :questions, shallow: true, expect: :index do
      resources :answers, shallow: true, expect: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  get "my_bages" => "bages#my_bages"

  get "bages" => "bages#index"

  namespace :admin do
    resources :bages, shallow:true do
      post "user_bages" => "user_bages#create"
      get "new_user_bage" => "user_bages#new"
    end

    resources :user_bages, shallow:true do
    end

    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow:true do
        resources :answers, shallow:true
      end
    end

    resources :gists, only: :index
  end

end

app/models/bage.rb
class Bage < ApplicationRecord
  has_many :users_bages
  has_many :bages, through: :users_bages

  validates :name, presence: true
  validates :url, presence: true
  validates :name, uniqueness: true
end

app/controllers/admin/bages_controller.rb
class Admin::BagesController < Admin::BaseController
  before_action :find_bages, only: %i[index]
  before_action :find_bage, only: %i[show edit update destroy]

  def index
  end

  def show

  end

  def new
    @bage = Bage.new
  end

  def edit
  end

  def create
    @bage = Bage.new(bage_params)

    if @bage.save
      redirect_to [:admin, @bage], notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @bage.update(bage_params)
      redirect_to [:admin, @bage]
    else
      render :new
    end
  end

  def destroy
    @bage.destroy
    redirect_to admin_bages_path
  end

  def user_bages
    @user_bage = UserBage.new(user_bage_params)

    if @user_bage.save
      redirect_to [:admin, @user_bage], notice: t('.success')
    else
      render :new
    end
  end

  private

  def bage_params
    params.require(:bage).permit(:name, :url, :rule, :rule_value)
  end

  def user_bage_params
    params.require(:user_bage).permit(:user_id, :bage_id)
  end

  def find_bages
    @bages = Bage.all
  end

  def find_bage
    @bage = Bage.find(params[:id])
  end
end

app/controllers/bages_controller.rb
class BagesController < ApplicationController
  before_action :find_bages, only: %i[index]
  before_action :find_my_bages, only: %i[my_bages]

  def index
    
  end

  def my_bages

  end

  private

  def find_bages
    @bages = Bage.all
  end

  def find_my_bages
    @my_bages = current_user.bages
  end

end

app/helpers/bages_helper.rb
module BagesHelper

  RULE_SELECT = ['all some category tests passed',
                 'successful passing of the test on the first attempt',
                 'successful passing all the tests of some level']

  def rule_select_key(key)
    RULE_SELECT[key]
  end

end

app/views/bages/_bage.html.erb
<tr>
  <td class="align-middle">
    <%= content_tag :span, bage.name %>
  </td>

  <td class="align-middle"><i class="material-icons md-36"> <%= bage.url %></i></td>
  <td class="align-middle">
    <%= content_tag :span, bage.rule %>
  </td>

  <td class="align-middle">
    <%= content_tag :span, bage.rule_value %>
  </td>
</tr>

app/views/bages/_my_bage.html.erb
<tr>
  <td class="align-middle">
    <%= content_tag :span, my_bage.name %>
  </td>

  <td class="align-middle"><i class="material-icons md-36"> <%= my_bage.url %></i></td>
  <td class="align-middle">
    <%= content_tag :span, bage.rule %>
  </td>

  <td class="align-middle">
    <%= content_tag :span, bage.rule_value %>
  </td>
</tr>

app/views/bages/index.html.erb
<h1>Badges</h1>

<% if @bages.present? %>
<table class="table-sm table-striped table-bordered">
  <thead class="thead-inverse">
    <tr>
    <th>Name</th>
    <th>Icon</th>
    <th>Rule</th>
    <th>Rule value</th>
    </tr>
  </thead>

  <%= render @bages %>

</table>
<% else %>
  <p>No badges</p>
<% end %>

<button type="button" >
  <%=link_to "Back", admin_tests_path %>
</button>

app/views/bages/my_bages.html.erb
<h1>You Badges</h1>

<%= link_to 'Show all badges', bages_path %>

<% if @my_bages.present? %>
<table class="table-sm table-striped table-bordered">
  <thead class="thead-inverse">
    <tr>
    <th>Name</th>
    <th>Icon</th>
    <th>Rule</th>
    <th>Rule value</th>
    </tr>
  </thead>

  <%= render @my_bages %>

</table>
<% else %>
  <p>You have no badges</p>
<% end %>

<button type="button" >
  <%=link_to "Back", root_path %>
</button>

app/views/bages/show.html.erb
<h1>Badges</h1>

<%= render 'shared/errors', resource: @bage %>

<% if current_user.user_bages.present? %>
<table class="table-sm table-striped table-bordered">
  <thead class="thead-inverse">
    <tr>
    <th>Name</th>
    <th>Icon</th>
    </tr>
  </thead>

  <%= render @bage %>

</table>
<% else %>
  <p>You have no badges</p>
<% end %>

<%= link_to "Back", admin_bages_path %>