config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: {sign_in: :login, sign_out: :logout},
              controllers: { registrations: 'users/registrations' }

  # resources :feedbacks, only: %i[index create]
  get "feedbacks" => "feedbacks#show"
  post "feedbacks" => "feedbacks#create"

  resources :tests, only: :index do
    resources :questions, shallow: true, expect: :index do
      resources :answers, shallow: true, expect: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  get "my_bages" => "bages#my_bages"

  get "bages" => "bages#index"

  namespace :admin do
    resources :bages, shallow:true do
      post "user_bages" => "user_bages#create"
      get "new_user_bage" => "user_bages#new"
    end

    resources :user_bages, shallow:true do
    end

    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow:true do
        resources :answers, shallow:true
      end
    end

    resources :gists, only: :index
  end

end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true
  validate :validate_count_answers

  scope :correct, -> { where(correct: true) }

  private

  def validate_count_answers
    errors.add(:body) unless Answer.where(question_id: self.question_id).count < 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bage.rb
class Bage < ApplicationRecord
  has_many :users_bages
  has_many :bages, through: :users_bages

  validates :name, presence: true
  validates :url, presence: true
  validates :name, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  validates :title, presence: true

  default_scope { order(title: :asc) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :test_passages
  has_many :current_questions, through: :test_passages
  has_many :answers
  belongs_to :test
  has_many :gists

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :questions
  has_many :test_passages
  has_many :users, through: :test_passages
  belongs_to :category
  belongs_to :author, class_name: "User"

  validates :title, presence: true
  validates :category_id, presence: true
  validates :level, numericality: { only_integer: true, greater_than: 0 }
  validates :title, uniqueness: { scope: :level }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }

  scope :by_level, -> (level) { where(level: level) }

  scope :by_category, -> (name_category) { joins(:category).
                                           where(categories: { title: name_category }) }

  def self.ordered_test_titles_by_category(name_category)
    self.by_category(name_category).order(title: :desc).pluck(:title)
  end

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  def accept!(answers_ids)
    if correct_answer?(answers_ids)
      self.correct_questions += 1
    end
    save!
  end

  def completed?
    self.current_question.nil?
  end

  def success?
    self.correct_questions / self.test.questions.count >= 0.85
  end

  def success_rate
    (((self.correct_questions).to_f / (self.test.questions.count).to_f) * 100).to_i
  end

  def progress
    (((self.index_current_question - 1).to_f / (self.test.questions.count).to_f) * 100).to_i
  end

  def index_current_question
    self.test.questions.pluck(:body).rindex(self.current_question.body) + 1
  end

  def timeout
    self.test.timer - (Time.now.to_i % 86400 - self.created_at.to_i % 86400) unless self.test.timer.nil?
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_update_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def correct_answer?(answers_ids)
    correct_answers_count = correct_answers.count

    (correct_answers_count == correct_answers.where(id: answers_ids).count) &&
    (correct_answers_count == answers_ids.count)
  end

  def correct_answers
    self.current_question.answers.correct
  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :created_tests, class_name: "Test", foreign_key: "author_id"
  has_many :gists
  has_many :user_bages
  has_many :bages, through: :user_bages

  validates :email, uniqueness: true

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.is_a?(Admin)
  end
end

app/models/user_bage.rb
class UserBage < ApplicationRecord
  belongs_to :user
  belongs_to :bage
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :set_answer , only: %i[show edit update destroy]
  before_action :find_question , only: %i[new create]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to [:admin, @answer], notice: 'Answer was successfully created'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to [:admin, @answer], notice: 'Answer was successfully created'
    else
      render :new
    end
  end

  def destroy
    @answer.destroy
    redirect_to [:admin, @answer.question]
  end

  private
  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/bages_controller.rb
class BagesController < ApplicationController
  before_action :find_bages, only: %i[index]
  before_action :find_my_bages, only: %i[my_bages]

  def index
    
  end

  def my_bages

  end

  private

  def find_bages
    @bages = Bage.all
  end

  def find_my_bages
    @my_bages = current_user.bages
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :find_test, only: %i[start]

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  FLASH_KEY = { 'notice' => 'alert alert-success', 'alert' => 'alert alert-danger' }.freeze

  def year_now
    Time.current.year
  end

  def flash_css_class(key)
    FLASH_KEY[key]
  end

end

app/helpers/bages_helper.rb
module BagesHelper

  RULE_SELECT = ['all some category tests passed',
                 'successful passing of the test on the first attempt',
                 'successful passing all the tests of some level']

  def rule_select_key(key)
    RULE_SELECT[key]
  end

end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    question.test.title
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper

  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3=> :hard }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end

end

app/helpers/user_bages_helper.rb
module UserBagesHelper
end

app/views/admin/answers/_answer.html.erb
<ul>

  <li><%= answer.body %> :
  <%= link_to 'Show', admin_answer_path(answer) %> |
  <%= link_to 'Edit', edit_admin_answer_path(answer) %> |
  <%= link_to 'Delete',
                   admin_answer_path(answer),
                   method: :delete,
                   data: { confirm: 'Are you sure?'} %></li>
</ul>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p><br>

  <p>
    <%= form.label :correct %><br>
    <%= form.check_box :correct, id: :answer_correct %>
  </p><br>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Editing Answer</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1>New Answer</h1>

<p>
  <%= @answer.body %>
</p>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', admin_question_path(@answer.question) %>

app/views/admin/answers/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Question</h1>

<p>
  <%= @answer.question.body %>
</p>

<h2>Answer</h2>

<p>
  <b>Body:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Edit', edit_admin_answer_path(questions_id: params[:id]) %> |
<%= link_to 'Back', admin_question_path(@answer.question) %>

app/views/answers/_answer.html.erb
<ul>

  <li><%= answer.body %> :
  <%= link_to 'Show', answer_path(answer) %> |
  <%= link_to 'Edit', edit_answer_path(answer) %> |
  <%= link_to 'Delete',
                   answer_path(answer),
                   method: :delete,
                   data: { confirm: 'Are you sure?'} %></li>
</ul>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Question</h1>

<p>
  <%= @answer.question.body %>
</p>

<h2>Answer</h2>

<p>
  <b>Body:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Edit', edit_answer_path(questions_id: params[:id]) %> |
<%= link_to 'Back', question_path(@answer.question) %>